# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: 2026 Simon Dorrer, Harald Pretl and Vasil Yordanov
# SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
# Description: Shared helpers for the analytical (gm/ID) sizing flow of all
# macros.
#
# Each analog macro keeps two small files in scripts/sizing/:
#   specs_<cell>.py   - the circuit specifications (plain-Python constants;
#                       derived values like VCM = VDD / 2 are fine)
#   sizing_<cell>.py  - the topology-specific gm/ID equations
# `make sizing` runs the latter, which uses the Report class below to tee
# every result line to stdout AND into a Markdown report
# (scripts/sizing/sizing_<cell>.md) that is committed to git. Anyone copying
# the circuit reads that report to see which specs were given and what the
# gm/ID calculation returned.
#
# The report deliberately carries no timestamp or git hash: re-running
# `make sizing` with unchanged specs produces a byte-identical file, so git
# diffs stay meaningful and a stale report is detectable by regenerating.
#
# Import from a macro sizing script with:
#   REPO_ROOT = Path(__file__).resolve().parents[4]
#   sys.path.insert(0, str(REPO_ROOT / "scripts" / "sizing"))
#   from sizing_common import Report, load_table, calculate_finger_options
# ============================================

from pathlib import Path

# Shared SG13G2 lookup tables (generated with the pygmid techsweep flow)
DATA_DIR = Path(__file__).resolve().parent / "data"


def load_table(device):
    """Load a shared SG13G2 gm/ID lookup table, e.g. load_table('sg13g2_lv_nmos').

    Available tables: sg13g2_{lv,hv}_{nmos,pmos}.
    Lookup parameters: VGS, VDS, VSB, L, W, NFING, ID, VT, GM, GMB, GDS, CGG,
    CGB, CGD, CGS, CDD, CSS, STH, SFL. If not specified, the lookup uses
    minimum L, VDS = max(vgs)/2 = 0.75 V and VSB = 0. See
    macros/inverter/scripts/sizing/lookup_commands.py for a tour of the API.
    """
    from pygmid import Lookup  # lazy: only needed when a table is loaded
    return Lookup(str(DATA_DIR / f"{device}.mat"))


class Report:
    """Tee sizing results to stdout and accumulate a Markdown report.

    Single write path: everything shown in the terminal also lands in the
    report, so the committed report cannot diverge from what the script
    printed. Keep this API append-only (all macros share it):
      specs()   - echo the specs_<cell>.py file (terminal + fenced block)
      section() - start a new section
      value()   - one named quantity (consecutive calls form one table)
      text()    - free-text paragraph
      table()   - explicit table (e.g. finger-configuration options)
      write()   - save the Markdown report
    """

    _RULE = "-" * 60

    def __init__(self, cell, generator):
        self._md = [
            f"# `{cell}` — analytical (gm/ID) sizing report",
            "",
            f"> Auto-generated by `{generator}` — do not edit by hand.",
            "> Regenerate with `make sizing` from the macro root.",
        ]
        self._rows = []  # pending value() rows of the current section
        print("=" * 60)
        print(f"{cell} — analytical (gm/ID) sizing")
        print("=" * 60)

    def _flush_rows(self):
        if self._rows:
            self._md += ["", "| Quantity | Value | Note |", "|---|---|---|"]
            self._md += [f"| {n} | {v} | {note} |" for n, v, note in self._rows]
            self._rows = []

    @staticmethod
    def _fmt(value, fmt):
        return value if isinstance(value, str) else f"{float(value):{fmt}}"

    def specs(self, specs_file):
        """Echo the specifications file verbatim (provenance in the report)."""
        specs_file = Path(specs_file)
        body = specs_file.read_text().strip()
        print(f"\nSpecifications ({specs_file.name}):")
        print(self._RULE)
        print(body)
        print(self._RULE)
        self._flush_rows()
        self._md += ["", f"## Specifications (`{specs_file.name}`)", "",
                     "```python", body, "```"]

    def section(self, title):
        self._flush_rows()
        print(f"\n{title}")
        print(self._RULE)
        self._md += ["", f"## {title}"]

    def value(self, name, value, unit="", note="", fmt=".4g"):
        shown = self._fmt(value, fmt) + (f" {unit}" if unit else "")
        print(f"{name} = {shown}" + (f"    ({note})" if note else ""))
        self._rows.append((name, shown, note))

    def text(self, msg):
        self._flush_rows()
        print(msg)
        self._md += ["", msg]

    def table(self, headers, rows, title=None):
        self._flush_rows()
        cells = [[str(c) for c in row] for row in rows]
        widths = [max(len(h), *(len(r[i]) for r in cells)) if cells else len(h)
                  for i, h in enumerate(headers)]
        if title:
            print(f"\n{title}")
        print("  ".join(h.ljust(w) for h, w in zip(headers, widths)))
        for r in cells:
            print("  ".join(c.ljust(w) for c, w in zip(r, widths)))
        if title:
            self._md += ["", f"### {title}"]
        self._md += ["", "| " + " | ".join(headers) + " |",
                     "|" + "---|" * len(headers)]
        self._md += ["| " + " | ".join(r) + " |" for r in cells]

    def write(self, report_file):
        self._flush_rows()
        report_file = Path(report_file)
        report_file.write_text("\n".join(self._md) + "\n")
        print(f"\nWrote sizing report: {report_file}")


def calculate_finger_options(width1_um, width2_um, target_ratio,
                             min_finger_width=1.0, max_finger_width=20.0,
                             max_options=10, finger_width_step=1.0):
    """
    Calculate practicable finger configurations for two transistors maintaining
    their width ratio. Finger widths are constrained to multiples of
    finger_width_step. Only returns configurations with an even number of
    fingers, and both transistors get the SAME number of fingers.

    Parameters:
    -----------
    width1_um : float
        Width of first transistor in micrometers (e.g., PMOS)
    width2_um : float
        Width of second transistor in micrometers (e.g., NMOS)
    target_ratio : float
        Target width ratio (width1 / width2)
    min_finger_width : float
        Minimum practical finger width in micrometers (default: 1.0um)
    max_finger_width : float
        Maximum practical finger width in micrometers (default: 20.0um)
    max_options : int
        Maximum number of options to return (default: 10)
    finger_width_step : float
        Step size for finger width in micrometers (default: 1.0um)

    Returns:
    --------
    list of tuples : (nf, fw1, fw2, actual_ratio, error_percent)
        nf: number of fingers (same for both transistors)
        fw1: finger width for transistor 1
        fw2: finger width for transistor 2
        List of viable configurations sorted by error and preference
    """

    combinations = []

    # Try different even numbers of fingers
    # Start from 2 and go up to a reasonable maximum
    max_nf = int(max(width1_um, width2_um) / min_finger_width) + 2

    for nf in range(2, max_nf + 1, 2):  # Only even numbers
        # Calculate required finger widths for this number of fingers
        fw1_exact = width1_um / nf
        fw2_exact = width2_um / nf

        # Round to nearest finger_width_step
        fw1 = round(fw1_exact / finger_width_step) * finger_width_step
        fw2 = round(fw2_exact / finger_width_step) * finger_width_step

        # Check if both finger widths are within acceptable range
        if (min_finger_width <= fw1 <= max_finger_width and
            min_finger_width <= fw2 <= max_finger_width):

            # Calculate actual widths with rounded finger widths
            actual_width1 = nf * fw1
            actual_width2 = nf * fw2

            # Calculate actual ratio
            actual_ratio = actual_width1 / actual_width2

            # Calculate percentage error from target ratio
            error_percent = abs(actual_ratio - target_ratio) / target_ratio * 100

            # Add to combinations
            combinations.append((nf, fw1, fw2, actual_ratio, error_percent))

    # Sort by preference: minimize error (but less aggressive), then prefer good finger widths
    def preference_score(combo):
        nf, fw1, fw2, actual_ratio, error_percent = combo
        # Primary: minimize ratio error (less aggressive weight to allow more error)
        error_score = error_percent * 2
        # Secondary: prefer finger widths around 3-8um range
        width_score1 = abs(fw1 - 5.0)
        width_score2 = abs(fw2 - 5.0)
        # Tertiary: prefer fewer fingers
        finger_score = nf * 0.01
        return error_score + width_score1 + width_score2 + finger_score

    combinations.sort(key=preference_score)

    return combinations[:max_options]
